### PR TITLE
Fix: [Render] Support for CleanupPolicies

### LINKED ISSUE #740: [Render] Support for CleanupPolicies
### Description

The render utility needs to be updated to account for CleanupPolicies so they can be rendered to Markdown and displayed on the site.

### Slack discussion

_No response_

### PR DESCRIPTION
**Pull request by VedRatan**
## Related issue #

 Closes #740 

## Proposed Changes

 Added the rendering support for the Cleanup Policies by updating the render utility.

## Screenshot of the output
image

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by VedRatan** [comment]
@eddycharly any reviews? Or something extra needs to be done in this PR?

**Comment by chipzoller** [comment]
This change won't be applicable until the website actually has support to display Cleanup Policies. This is only one half of the complete story, so we need to add the second.

**Comment by VedRatan** [comment]
oh okay, I got it, I will send the fix in a day or two.

**Comment by chipzoller** [comment]
@VedRatan did you see above?

**Comment by VedRatan** [comment]
Yes I had looked into it, still finding the possible fix, will try to fix this soon.

**Comment by VedRatan** [comment]
@chipzoller I have added the checkbox for the cleanUp policies, we just need to render the policies in `others` folder to render them to the website according to the filters. I think this should work fine now. Please do let me know if something more is to be done.

**Comment by chipzoller** [comment]
Have you tested that this works end-to-end?

**Comment by VedRatan** [comment]
Yeah, I tested it, its working fine ATMO.

**Comment by chipzoller** [comment]
Can you show proof, please? I suggest adding a Markdown file manually that was rendered from the changes in your PR and adding it somewhere to the policies folder so the Netlify preview picks this all up.

**Comment by VedRatan** [comment]
Sure, below is the ss of the proof which renders the cleanup policy that was used by me to render the cleanup policy.

image

**Comment by chipzoller** [comment]
Thanks! And how about if you add the `description` annotation. That is getting rendered as well, right?

**Comment by VedRatan** [comment]
Yes, its also getting rendered as expected I had tested it as well.

**Comment by VedRatan** [comment]
Anything more to be done on this one @chipzoller, or are we good to go?

**Comment by chipzoller** [comment]
May be good but I'm on vacation. Will get this merged next week.

File: render/render.go [hunk 1]
```diff
@@ -55,15 +56,18 @@ func getPolicyType(yaml string) string {
 		return mutate
 	} else if yamlContainsPolicy(newYAML, validate) {
 		return validate
-	} else {
+	} else if yamlContainsPolicy(newYAML, verifyImages) {
 		return verifyImages
+	} else {
+		return cleanUp
```
Comment (chipzoller) [inline render/render.go:62]: I know this works, but honestly I think this is a bit lazy. Rather than assuming the type is always a cleanup policy by process of elimination, I would rather do this as a positive determination: If the apiVersion and kind say it's a cleanup policy then it's a cleanup policy. This is a different CRD than the `ClusterPolicy` and `Policy` which the render logic was set up to match. The reason this would be better is, if in the future, we want to start rendering Markdown from newer Kyverno CR types, we'll already have something to go on.

**Review by chipzoller — CHANGES_REQUESTED** [review]
I know what you've done "works" but I think there's a cleaner way to do this which is better.

File: render/render.go (hunk 1 above)
Comment (VedRatan) [reply render/render.go]: Updated the code.

**Comment by VedRatan** [comment]
Anything more to be done @chipzoller ? Or any more reviews in the implementation?

**Comment by chipzoller** [comment]
@eddycharly, would you please review the code portion?

**Comment by chipzoller** [comment]
Ping @eddycharly

**Comment by eddycharly** [comment]
LGTM

**Review by eddycharly — APPROVED** [review]

**Comment by VedRatan** [comment]
Thanks for merging this one @eddycharly @chipzoller .
